name: Feature Request
description: Got an idea for a feature that can make Flameshot even better? Propose your suggestion here!
body:
- type: markdown
  attributes:
    value: |
      1. Please speak English, this is the language all maintainers can speak and write.
      2. Please only use this form to submit feature request and not bugs or questions.
      3. Please take a moment to check that your feature hasn't already been suggested.
- type: textarea
  id: description
  attributes:
    label: Feature Description
    placeholder: |
      I think it would be great if ...
  validations:
    required: true
